# Generated by Django 6.0.6 on 2026-07-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
